#pragma once

#include <stdint.h>
#include <modules/platform_stm32f302x8/platform_stm32f302x8.h>

#define BOARD_PAL_LINE_SPI_3_SCK PAL_LINE(GPIOB,3) // AF6
#define BOARD_PAL_LINE_SPI_3_MISO PAL_LINE(GPIOB,4) // AF6
#define BOARD_PAL_LINE_SPI_3_MOSI PAL_LINE(GPIOB,5) // AF6
#define BOARD_PAL_LINE_SPI_CS_ICM PAL_LINE(GPIOB,0)
#define BOARD_PAL_LINE_SPI_CS_FLOW PAL_LINE(GPIOA,15)
#define BOARD_PAL_LINE_FLOW_NRST PAL_LINE(GPIOA,6)
#define BOARD_PAL_LINE_FLOW_INT PAL_LINE(GPIOA,5)
#define BOARD_PAL_LINE_LED_TRIG PAL_LINE(GPIOA,7)
#define BOARD_PAL_LINE_AMBER_LED PAL_LINE(GPIOA,0)
#define BOARD_PAL_LINE_ICM_IRQ PAL_LINE(GPIOA,8)
#define BOARD_PAL_LINE_ICM_FSYNC PAL_LINE(GPIOA,4)
#define BOARD_PAL_LINE_I2C_2_SCL PAL_LINE(GPIOA,9) // AF4
#define BOARD_PAL_LINE_I2C_2_SDA PAL_LINE(GPIOA,10) // AF4
#define BOARD_PAL_LINE_I2C_1_SCL PAL_LINE(GPIOB,6) // AF4
#define BOARD_PAL_LINE_I2C_1_SDA PAL_LINE(GPIOB,7) // AF4
#define BOARD_PAL_LINE_DEBUG_TX PAL_LINE(GPIOA,2)
#define BOARD_PAL_LINE_DEBUG_RX PAL_LINE(GPIOA,3)
#define BOARD_PAL_LINE_CAN_RX PAL_LINE(GPIOA,11) // AF9
#define BOARD_PAL_LINE_CAN_TX PAL_LINE(GPIOA,12) // AF9
#define VL53L1X_I2C_BUS 2
#define ICM_SPI_BUS 3
#define FLOW_SPI_BUS 3
